/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicalInterface;

import Actions.Action;
import SalesInvoice.InvoiceDetails;
import SalesInvoice.InvoiceDetailsTable;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 *
 * @author rfekry
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceTable = new javax.swing.JTable();
        invoiceTable.getSelectionModel().addListSelectionListener(action1);
        createInvoiceBtn = new javax.swing.JButton();
        createInvoiceBtn.addActionListener(action1);
        deleteInvoiceBtn = new javax.swing.JButton();
        deleteInvoiceBtn.addActionListener(action1);
        invoiceNoLbl1 = new javax.swing.JLabel();
        invoiceDateLbl = new javax.swing.JLabel();
        custNameLbl = new javax.swing.JLabel();
        invoiceTotalLbl1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        invoicesItemsTable = new javax.swing.JTable();
        javax.swing.JButton createItemBtn = new javax.swing.JButton();
        createItemBtn.addActionListener(action1);
        deleteItemlBtn = new javax.swing.JButton();
        deleteItemlBtn.addActionListener(action1);
        InvoiceNo_label = new javax.swing.JLabel();
        InvioceTotal_Label = new javax.swing.JLabel();
        invoiceDateTxt = new javax.swing.JTextField();
        cutomerNameTxt = new javax.swing.JTextField();
        invoiceItemsLbl1 = new javax.swing.JLabel();
        invoicesTbl_Label = new javax.swing.JLabel();
        MenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadFileItem1 = new javax.swing.JMenuItem();
        loadFileItem1.addActionListener(action1);
        saveFileItem2 = new javax.swing.JMenuItem();
        saveFileItem2.addActionListener(action1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Date", "Customer", "Total"
            }
        ));
        jScrollPane1.setViewportView(invoiceTable);

        createInvoiceBtn.setText("Create New Invoice");

        deleteInvoiceBtn.setText("Delete Invoice");
        deleteInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInvoiceBtnActionPerformed(evt);
            }
        });

        invoiceNoLbl1.setText("Invioce Number");

        invoiceDateLbl.setText("Invoice Date");

        custNameLbl.setText("Customer Name");

        invoiceTotalLbl1.setText("Invoice Total");

        invoicesItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Item Name", "Item Price", "Count", "Item Total"
            }
        ));
        jScrollPane2.setViewportView(invoicesItemsTable);

        createItemBtn.setText("Create New Item");

        deleteItemlBtn.setText("Delete Item");
        deleteItemlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemlBtnActionPerformed(evt);
            }
        });

        invoiceItemsLbl1.setText("Invoice Items");

        invoicesTbl_Label.setText("Invoices Table");

        fileMenu.setText("File");

        loadFileItem1.setText("Load File");
        loadFileItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(loadFileItem1);

        saveFileItem2.setText("Save File");
        fileMenu.add(saveFileItem2);

        MenuBar1.add(fileMenu);

        setJMenuBar(MenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(createInvoiceBtn)
                        .addGap(59, 59, 59)
                        .addComponent(deleteInvoiceBtn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(invoiceNoLbl1)
                                    .addComponent(invoiceTotalLbl1))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InvioceTotal_Label)
                                    .addComponent(InvoiceNo_label)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(invoiceDateLbl)
                                    .addComponent(custNameLbl))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(cutomerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(invoiceDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(invoiceItemsLbl1))
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createItemBtn)
                        .addGap(76, 76, 76)
                        .addComponent(deleteItemlBtn)
                        .addGap(103, 103, 103))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invoicesTbl_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceNoLbl1)
                    .addComponent(InvoiceNo_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invoicesTbl_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceDateLbl)
                            .addComponent(invoiceDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custNameLbl)
                            .addComponent(cutomerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceTotalLbl1)
                            .addComponent(InvioceTotal_Label))
                        .addGap(22, 22, 22)
                        .addComponent(invoiceItemsLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createItemBtn)
                            .addComponent(deleteItemlBtn)
                            .addComponent(deleteInvoiceBtn)
                            .addComponent(createInvoiceBtn))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteItemlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemlBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteItemlBtnActionPerformed

    private void deleteInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInvoiceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteInvoiceBtnActionPerformed

    private void loadFileItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadFileItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InvioceTotal_Label;
    private javax.swing.JLabel InvoiceNo_label;
    private javax.swing.JMenuBar MenuBar1;
    private javax.swing.JButton createInvoiceBtn;
    private javax.swing.JLabel custNameLbl;
    private javax.swing.JTextField cutomerNameTxt;
    private javax.swing.JButton deleteInvoiceBtn;
    private javax.swing.JButton deleteItemlBtn;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel invoiceDateLbl;
    private javax.swing.JTextField invoiceDateTxt;
    private javax.swing.JLabel invoiceItemsLbl1;
    private javax.swing.JLabel invoiceNoLbl1;
    private javax.swing.JTable invoiceTable;
    private javax.swing.JLabel invoiceTotalLbl1;
    private javax.swing.JTable invoicesItemsTable;
    private javax.swing.JLabel invoicesTbl_Label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadFileItem1;
    private javax.swing.JMenuItem saveFileItem2;
    // End of variables declaration//GEN-END:variables
   
    private ArrayList<InvoiceDetails> allInvoices;
    private InvoiceDetailsTable invTable;

    public InvoiceDetailsTable getInvTable() {
     
        return invTable;
    }

    public void setInvTable(InvoiceDetailsTable invTable) {
        this.invTable = invTable;
    }
    
    private Action action1 = new Action(this);

    public ArrayList<InvoiceDetails> getAllInvoices() {
        return allInvoices;
    }

    public void setAllInvoices(ArrayList<InvoiceDetails> allInvoices) {
        this.allInvoices = allInvoices;
    }

    public JTextField getCutomerNameTxt() {
        return cutomerNameTxt;
    }

    public void setCutomerNameTxt(JTextField cutomerNameTxt) {
        this.cutomerNameTxt = cutomerNameTxt;
    }

    public JTextField getInvoiceDateTxt() {
        return invoiceDateTxt;
    }

    public void setInvoiceDateTxt(JTextField invoiceDateTxt) {
        this.invoiceDateTxt = invoiceDateTxt;
    }

    public JTable getInvoiceTable() {
        return invoiceTable;
    }

    public void setInvoiceTable(JTable invoiceTable) {
        this.invoiceTable = invoiceTable;
    }

    public JLabel getInvioceTotal_Label() {
        return InvioceTotal_Label;
    }

    public void setInvioceTotal_Label(JLabel InvioceTotal_Label) {
        this.InvioceTotal_Label = InvioceTotal_Label;
    }

 

    public JTable getInvoicesItemsTable() {
        return invoicesItemsTable;
    }

    public void setInvoicesItemsTable(JTable invoicesItemsTable) {
        this.invoicesItemsTable = invoicesItemsTable;
    }

    public JLabel getInvoiceNo_label() {
        return InvoiceNo_label;
    }

    public void setInvoiceNo_label(JLabel InvoiceNo_label) {
        this.InvoiceNo_label = InvoiceNo_label;
    }

    public Action getAction1() {
        return action1;
    }
    
 
    
    public int getNextNum()
    {
        int no=0;
        for(InvoiceDetails inv : allInvoices)
        {
            if(inv.getInvoiceNo()>no)
                no=inv.getInvoiceNo();
        }
        return no;
    }
}
